import { zipSync, strToU8 } from "fflate";
import { ICON_PNG_B64 } from "../assets/iconPng";

export type McpbGeneratorInput = {
  version: string;
  port: number;
  token: string;
};

// Entry-point shim satisfying the entry_point schema requirement.
// Token and URL are baked in; process.env.* overrides are accepted so
// the values can be overridden without re-generating the bundle.
function buildShim(input: McpbGeneratorInput): string {
  const url = `http://127.0.0.1:${input.port}/mcp`;
  return `#!/usr/bin/env node
const { spawn } = require("child_process");
const url = process.env.MCP_REMOTE_URL || ${JSON.stringify(url)};
const token = process.env.MCP_REMOTE_TOKEN || ${JSON.stringify(input.token)};
const args = ["-y", "mcp-remote", url];
if (token) args.push("--header", \`Authorization: Bearer \${token}\`);
spawn("npx", args, { stdio: "inherit" }).on("exit", (c) => process.exit(c ?? 0));
`;
}

function buildManifest(input: McpbGeneratorInput): Record<string, unknown> {
  const url = `http://127.0.0.1:${input.port}/mcp`;
  return {
    manifest_version: "0.3",
    name: "obsidian-mcp-connector",
    display_name: "Obsidian MCP Connector",
    version: input.version,
    description:
      "Access your Obsidian vault (semantic search, notes, Templater prompts) via MCP.",
    author: { name: "Stefano Ferri" },
    icon: "icon.png",
    server: {
      type: "node",
      entry_point: "server/index.js",
      mcp_config: {
        command: "npx",
        args: [
          "-y",
          "mcp-remote",
          url,
          "--header",
          `Authorization: Bearer ${input.token}`,
        ],
      },
    },
    // No user_config: token and port are embedded so Claude Desktop
    // installs with zero prompts. This bundle is generated by the plugin
    // from the live credentials — it should not be shared publicly.
  };
}

export function generateMcpb(input: McpbGeneratorInput): Uint8Array {
  const manifest = buildManifest(input);
  const manifestBytes = strToU8(JSON.stringify(manifest, null, 2));
  const shimBytes = strToU8(buildShim(input));
  const iconBytes = Uint8Array.from(atob(ICON_PNG_B64), (c) => c.charCodeAt(0));
  return zipSync({
    "manifest.json": manifestBytes,
    "server/index.js": shimBytes,
    "icon.png": iconBytes,
  });
}
